# Generated by Django 4.2 on 2023-04-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
    ]
